### ISSUE TITLE
PR24 for UTC Support Causing Issues

### ISSUE THREAD

**Issue by BHollowell** [georgeherby/MADevice#28] opened 2020-03-30 18:36 UTC
It seems that PR24, which converted "datetime.now()" to "datetime.utcnow()" has broken this script for Madmin instances which are storing Last Update time using a different timezone. I've attached an image with the appropriate debug information. Please let me know if you need anything else to help resolve this issue.
![debug](https://user-images.githubusercontent.com/7934894/77948685-c808cb80-7293-11ea-860c-c5afd66d92df.png)

**Comment by BadWolf0081** [comment] 2020-04-02 10:45
I have this issue now too, all my devices are being reported as 4 hours overdue because of the change.  I think this was created to handle something which was already fixed in MAD.

**Comment by gcm-explo1t** [comment] 2020-04-03 21:26
Have this problem the other way round.
The boxes are down for already 2 hours but not detected. Only when they breach the 3 hours mark:
```
Apr 03 23:20:31 mad-munich python3[24118]:  [04-03 23:20:31] [     ScanChecker] [         alert:131] [   DEBUG] Brownandroidbox1 Last Proto Date Time: 2020-04-03 21:21:49
Apr 03 23:20:31 mad-munich python3[24118]:  [04-03 23:20:31] [     ScanChecker] [         alert:132] [   DEBUG] Brownandroidbox1 Last Acceptable Time: 2020-04-03 21:00:31.842317
Apr 03 23:20:31 mad-munich python3[24118]:  [04-03 23:20:31] [     ScanChecker] [         alert:144] [    INFO] Brownandroidbox1 did not breach the time threshold
```
![screen](https://user-images.githubusercontent.com/27489254/78406231-8022d500-7602-11ea-8f9f-3a8727d12931.png)

**Comment by gcm-explo1t** [comment] 2020-04-03 21:33
After reverting the [PR](https://github.com/georgeherby/MADevice/pull/24) it worked again as intended.

**Comment by georgeherby** [comment] 2020-04-06 13:44
Reverted the PR, apologies

**Closed** 2020-04-06 13:44 UTC
